# Generated by Django 4.0.3 on 2024-06-18 21:46

from django.db import migrations, models
import dovolena.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dovolena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinace', models.CharField(blank=True, help_text='Zadejte destinace', max_length=20, null=True, verbose_name='Destinace')),
                ('zacatek_terminu', models.DateField(error_messages={'blank': 'Začátek termínu musí být vyplněný'}, help_text='Zadejte začátek vaší dovolené', verbose_name='Začátek dovolené')),
                ('konec_terminu', models.DateField(error_messages={'blank': 'Konec termínu musí být vyplněný'}, help_text='Zadejte konec vaší dovolené', verbose_name='Konec dovolené')),
            ],
            options={
                'verbose_name': 'Dovolená',
                'verbose_name_plural': 'Dovolené',
                'ordering': ['destinace', 'zacatek_terminu', 'konec_terminu'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('misto_odletu', models.CharField(choices=[('BRNO', 'Brno'), ('PRAHA', 'Praha'), ('OSTRAVA', 'Ostrava')], error_messages={'blank': 'Místo odletu musí být zadáno'}, help_text='Zadej místo odletu', max_length=7, verbose_name='Místo odletu')),
            ],
            options={
                'verbose_name': 'Let',
                'verbose_name_plural': 'Lety',
            },
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Hodnocení musí být mezi 1 a 5', validators=[dovolena.models.validate_rating], verbose_name='Rating')),
                ('review', models.TextField(blank=True, help_text='Přidejte recenzi', null=True, verbose_name='Recenze')),
            ],
            options={
                'verbose_name': 'Recenze',
                'verbose_name_plural': 'Recenze',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocet_ucastniku', models.IntegerField(error_messages={'blank': 'Počet účastníků musí být vyplněný'}, help_text='Zadejte počet účastníků', verbose_name='Počet účastníků')),
                ('celkem_cena', models.DecimalField(decimal_places=2, error_messages={'blank': 'Celková cena musí být vyplněná'}, help_text='Zadejte celkovou cenu', max_digits=10, verbose_name='Celková cena')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ucastnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(error_messages={'blank': 'Jméno účastníka musí být vyplněno'}, help_text='Zadejte jméno účastníka', max_length=80, verbose_name='Jméno účastníka')),
                ('prijmeni', models.CharField(error_messages={'blank': 'Příjmení účastníka musí být vyplněno'}, help_text='Zadejte příjmení účastníka', max_length=50, verbose_name='Příjmení účastníka')),
                ('email', models.EmailField(error_messages={'blank': 'E-mail účastníka musí být vyplněný'}, help_text='Zadejte E-mail účastníka', max_length=50, verbose_name='E-mail účastníka')),
                ('telefon', models.CharField(error_messages={'blank': 'Telefon účastníka musí být vyplněný'}, help_text='Zadejte telefonní číslo', max_length=15, verbose_name='Telefon účastníka')),
                ('datum_narozeni', models.DateField(error_messages={'blank': 'Datum narození musí být vyplněný'}, help_text='Zadejte datum narození', verbose_name='Datum narození účastníka')),
            ],
            options={
                'verbose_name': 'Účastník',
                'verbose_name_plural': 'Účastníci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
    ]
